services:
  - type: web
    name: bot-discord
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
